package com.example.uts_khaliq

val makananList = listOf<Makanan>(
    Makanan(R.drawable.lasagna,"Lasagna","$10","Italia", "Lasagna atau lasagne adalah pasta yang dipanggang di oven dan merupakan makanan tradisional Italia. Lasagna sendiri secara harfiah adalah lasagne yang berisikan daging. Lasagna sendiri dapat diisi dengan banyak isian lainnya seperti daging, sayur-sayuran, ayam, makanan laut dan sebagainya sesuai selera"),
    Makanan(R.drawable.kari,"Kari","$6","India", "Kari merupakan nama untuk jenis masakan yang dimasak dengan berbagai bumbu rempah hingga mempunyai cita rasa yang kuat dan pedas"),
    Makanan(R.drawable.tacos, "Tacos", "$3", "Mexico", "Tacos atau taco adalah makanan khas Mexico yang berisi sayuran, daging, dan saus. Isian tersebut diselimuti oleh kulit tortila"),
    Makanan(R.drawable.pho, "Pho", "$2", "Vietnam", "Pho adalah makanan khas vietnam yang terbuat dari mie putih yang terbuat dari tepung beras dan daging serta kaldu yang terbuat dari tulang. Pho bisa ditambahkan dengan sayuran-sayuran, kecap ikan, cabai rawit, dan lain sebagainya"),
    Makanan(R.drawable.poke, "Poke", "$3", "Hawai","Poke bowl merupakan makanan yang terbuat dari kumpulan sayuran dan daging mentah segar serta menggunakan saus khusus. Semua bahan makanan tersebut kemudian dicampur seperti salad"),
    Makanan(R.drawable.pastel_de_nata, "Pastel de nata", "$2", "Portugal","Pastel de nata adalah kue tart yang berasal dari Portugis. Seperti yang dapat dilihat di gambar, pastel de nata memiliki tampilan seperti pie. Bahan utama dari makanan ini adalah telur"),
    Makanan(R.drawable.rendang, "Rendang", "$2", "Indonesia", "Siapa yang tidak kenal dengan rendang, makanan yang satu ini? Makanan yang terbuat dari olahan daging ini merupakan makanan unik yang berasal dari Indonesia. Rendang termasuk makanan yang banyak digemari oleh banyak orang, loh!"),
    Makanan(R.drawable.massaman_curry, "Massaman curry", "$4","Thailand","Massaman curry adalah sebuah makanan yang terbuat dari massaman curry paste, yaitu sebuah kari yang terbuat dari kacang tanah, lengkuas, kapulaga, kayumanis, dan sebagainya. Selain itu, bahan utama dari massaman curry adalah santan dan protein seperti daging sapi, daging ayam, tahu, tempe, dan lain-lain"),
    Makanan(R.drawable.fondue,"Fondue", "$30", "Swiss","Fondue merupakan makanan khas Swiss yang terbuat dari keju yang dilelehkan. Fondue biasanya dimakan dengan potongan roti, atau daging yang ditusuk dengan garpu dan dicelupkan ke dalam lelehan keju atau fondue yang sudah dibuat"),
    Makanan(R.drawable.pierogi, "Pierogi","$9","Poland","Makanan yang berasal dari Polandia ini terbuat dari tepung terigu dengan isian kentang tumbuk, daging, jamur, keju, dan lain-lain tergantung selera. Seperti yang dapat dilihat pada gambar, Pierogi dibentuk seperti makanan pangsit yang ada di Indonesia"),
    Makanan(R.drawable.arepas, "Arepas", "$30", "Venezuela", "Arepas merupakan makanan khas Venezuela yang memiliki tekstur garing di luar dan lembut di dalam. Bahan utama dari arepas adalah jagung giling yang sudah dimasak dalam air dan sudah dikeringkan. Isian dari makanan arepas ini juga beragam, ada pisang, kacang hitam, jamur, tahu, dan sebagainya"),
    Makanan(R.drawable.hummus,"Hummus", "$5","Middle East","Hummus adalah makanan yang berasal dari Timur Tengah, makanan ini terbuat dari kacang arab dan di oleh sehingga menghasilkan tekstur yang lembut dan terlihat seperti bubur"),
    Makanan(R.drawable.poutine, "Poutine", "$12", "Canada", "Seperti yang dapat dilihat, Poutine adalah makanan khas dari Canada yang terbuat dari kentang goreng. Kentang tersebut dilumuri oleh keju dan saus kental berwarna coklat yang terbuat dari tepung maizena"),
    Makanan(R.drawable.seafood_paella,"Seafood Paella","$24","Spain", "Seafood paella sekilas memiliki tampilan seperti nasi goreng, karena sama-sama terbuat dari nasi, biasanya seafood paella dibuat dari bomba rice. Di atas nasi tersebut terdapat kumpulan seafood seperti udang, kerang, cumi, dan lain sebagainya"),
    Makanan(R.drawable.chicken_rice,"Chicken Rice","$5","Singapore", "Chicken rice atau dalam bahasa Indonesia dikenal dengan nasi ayam, merupakan makanan khas dari negara tetangga, yaitu Singapura. Ayam tersebut direbus hingga matang kemudian disajikan dengan nasi, bumbu jahe, dan juga saus cabai")
)